import os
import json
import logging
from typing import Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import firebase_admin
from firebase_admin import auth as fb_auth, credentials
from app.core.config import settings

logger = logging.getLogger(__name__)
security = HTTPBearer(auto_error=False)

# Initialize Firebase Admin SDK
if not firebase_admin._apps:
    try:
        if settings.FIREBASE_CREDENTIALS_JSON:
            cred_dict = json.loads(settings.FIREBASE_CREDENTIALS_JSON)
            cred = credentials.Certificate(cred_dict)
            firebase_admin.initialize_app(cred, {"projectId": settings.FIREBASE_PROJECT_ID})
        elif settings.FIREBASE_CREDENTIALS_PATH and os.path.exists(settings.FIREBASE_CREDENTIALS_PATH):
            cred = credentials.Certificate(settings.FIREBASE_CREDENTIALS_PATH)
            firebase_admin.initialize_app(cred, {"projectId": settings.FIREBASE_PROJECT_ID})
        else:
            # Fall back to default Application Default Credentials (e.g. on Google Cloud Run)
            firebase_admin.initialize_app(options={"projectId": settings.FIREBASE_PROJECT_ID})
    except Exception as e:
        logger.warning(f"Firebase Admin SDK initialization notice: {e}")

class AuthenticatedUser:
    def __init__(self, firebase_uid: str, email: Optional[str] = None, phone: Optional[str] = None):
        self.uid = firebase_uid
        self.firebase_uid = firebase_uid
        self.email = email
        self.phone = phone

async def get_current_user_token(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security)
) -> AuthenticatedUser:
    if not credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing Bearer authentication token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    token = credentials.credentials

    # Strict check: production rejects any test token bypass immediately
    if settings.ENVIRONMENT == "production" and token.startswith("test_token:"):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Development test tokens are not permitted in production",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # Local development & CI automated test bypass only if explicitly non-production
    if settings.ENVIRONMENT != "production" and token.startswith("test_token:"):
        parts = token.split(":")
        uid = parts[1] if len(parts) > 1 else "test_user"
        email = parts[2] if len(parts) > 2 else f"{uid}@test.local"
        return AuthenticatedUser(firebase_uid=uid, email=email)

    try:
        # Cryptographically verify Firebase ID token via Firebase Admin SDK
        decoded_token = fb_auth.verify_id_token(token, check_revoked=False)
        uid = decoded_token.get("uid")
        if not uid:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token: missing UID"
            )
        return AuthenticatedUser(
            firebase_uid=uid,
            email=decoded_token.get("email")
        )
    except Exception as fb_err:
        # In non-production only, allow decoding local test JWT if generated by dev auth router
        if settings.ENVIRONMENT != "production":
            from app.modules.auth.security_jwt import decode_access_token
            local_payload = decode_access_token(token)
            if local_payload and "sub" in local_payload:
                return AuthenticatedUser(
                    firebase_uid=str(local_payload["sub"]),
                    email=local_payload.get("email")
                )

        logger.warning(f"Firebase token verification failed: {fb_err}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

